export const SET_STATE = "SET_STATE"
export const LOG = "LOG"
export const SET_STATUS = "SET_STATUS"
export const SET_FILEPATH = "SET_FILEPATH"
export const SET_CONFIG = "SET_CONFIG"
export const ADD_CONFIG = "ADD_CONFIG"
export const ADD_TEMPLATE = "ADD_TEMPLATE"