export const SET_STATE = "SET_STATE";
export const LOG = "LOG";
export const SET_STATUS = "SET_STATUS";
export const SET_FILEPATH = "SET_FILEPATH";
export const SET_CONFIG = "SET_CONFIG";
export const SET_CONFIGS = "SET_CONFIGS";
export const UPDATE_CONFIGKEY = "UPDATE_CONFIGKEY";
export const UPDATE_CONFIG= "UPDATE_CONFIG";
export const ADD_CONFIG = "ADD_CONFIG";
export const REMOVE_CONFIG = "REMOVE_CONFIG";
export const ADD_TEMPLATE = "ADD_TEMPLATE";
export const SET_TEMPLATES = "SET_TEMPLATES";
export const SET_TEMPLATE = "SET_TEMPLATE";
export const UPDATE_ADJUSTMENT = "UPDATE_ADJUSTMENT"
export const SET_PRINTER = "SET_PRINTER"
export const SET_UPDATE = "SET_UPDATE"
export const SET_USERNAME = "SET_USERNAME"
