export enum WindowEvent {
    Close = "close",
    Minimize = "minimize",
    Template = "template",
    Print = "print",
    File = "file",
    Printers = "printers",
    DYMOWebServices = "dymo_web_services",
    FileOpen = "open-with",
    Error = "main-error",
    Ping = "ping",
    GetTemplates = "get-templates",
    GetTemplate = "get-template",
    AddTemplate = "add-template",
    UpdateTemplate = "update-template",
    DeleteTemplate = "delete-template",
    GetConfigs = "get-configs",
    GetConfig = "get-config",
    AddConfig = "add-confg",
    UpdateConfig = "update-config",
    DeleteConfig = "delete-config",
    GetVariants = "get-variants",
    GetVariant = "get-variant",
    AddVariant = "add-variant",
    UpdateVariant = "update-variant"
}